# Generated by Django 2.1.7 on 2019-04-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actiontype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=20, null=True)),
                ('accept', models.IntegerField(default=0)),
                ('reject', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuitmentSite.Actiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, null=True)),
                ('lname', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('d_b', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('organisation', models.CharField(max_length=20, null=True)),
                ('experience', models.FloatField(default=0)),
                ('re_experience', models.FloatField(default=0)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('skills', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('action_type', models.CharField(max_length=20, null=True)),
                ('action', models.IntegerField(default=0)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='employee_details_list',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuitmentSite.Employeedetails'),
        ),
    ]
